<a href="https://colab.research.google.com/github/luckysouthchou/551/blob/master/np_broadcasting_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import numpy as np
import pandas as pd


In [65]:
a= np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
a = a.reshape(2, 2, 3)

In [67]:
sigma = np.array([[2, 3], [4, 5], [5, 7]])

In [74]:
sigma.shape

(3, 2)

In [77]:
sigma

array([[2, 3],
       [4, 5],
       [5, 7]])

In [75]:
n = sigma[:, None, :]

In [73]:
n.shape

(3, 1, 2)

In [76]:
n

array([[[2, 3]],

       [[4, 5]],

       [[5, 7]]])

In [70]:
b = sigma[:, :, None]

In [72]:
b.shape

(3, 2, 1)

In [78]:
d = sigma[None, :, :]

In [79]:
d

array([[[2, 3],
        [4, 5],
        [5, 7]]])

In [80]:
d.shape

(1, 3, 2)

In [81]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [85]:
c = a + 1

In [86]:
b = a ** 2

In [87]:
b + c

array([[[  1,   3,   7],
        [ 13,  21,  31]],

       [[ 43,  57,  73],
        [ 91, 111, 133]]])